In [7]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

import warnings
warnings.filterwarnings('ignore')

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
print(X_new)


[[2]
 [4]
 [6]]


In [11]:
#2.
from sklearn.feature_selection import VarianceThreshold

#X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]] # Error: All data are 0 values
X = [[1, 2, 1], [1, 1, 3], [3, 1, 1]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)
print(X_new)

[[1 2 1]
 [1 1 3]
 [3 1 1]]


In [15]:
#3.
from sklearn.metrics.pairwise import cosine_similarity
#data = [[5, 0, 3], [0, 0, 0]] # Error: 2nd array data is 0 values
data = [[5, 0, 3], [1, 2, 3]]
similarity = cosine_similarity(data)
print(similarity)

[[1.         0.64168895]
 [0.64168895 1.        ]]


In [17]:
#4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
print(X_new)

[[1]
 [3]
 [5]]


In [20]:
#5.
import pandas as pd # Library missed to import
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    #'rate': [5, 4, 3] Error: column name mismatched
    'rating': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating') 
pivot

item   I1   I2
user          
A     5.0  3.0
B     NaN  4.0

In [24]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
#pca = PCA(n_components=3) Error: n_components totally we have 2 in X but given as 3
pca = PCA(n_components=2) 
X_new = pca.fit_transform(X)
X_new

array([[-1.41421356,  0.        ],
       [ 1.41421356,  0.        ]])

In [33]:
#7.
import numpy as np
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
ratings = ratings.fillna(0) # replace None to 0
sim = cosine_similarity(ratings.T)
sim

array([[1.        , 0.        , 0.38348249],
       [0.        , 1.        , 0.89442719],
       [0.38348249, 0.89442719, 1.        ]])

In [27]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


Predicted Score: 2.5


In [34]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


[[0 2]]


In [37]:
#10.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1]).reshape(1,-1) # add reshape
b = np.array([0, 1, 1]).reshape(1,-1)  # add reshape

sim = cosine_similarity(a, b)
print("Similarity:", sim)

Similarity: [[0.5]]
